apiVersion: apps/v1
kind: Deployment
metadata:
  name: even-debug
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - image: alpine
        command:
          - "sleep"
          - "604800"
        imagePullPolicy: IfNotPresent
        name: alpine
