apiVersion: apps/v1
kind: Deployment
metadata:
  name: GPU-sleepy-deployment
  labels:
    app: sleep
spec:
  selector:
    matchLabels:
      app: sleep
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: alpine
          command: ["sleep", "3600"]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              nvidia.com/gpu: 1
      restartPolicy: Always
